CREATE TABLE IF NOT EXISTS USER(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS PRODUCT(
    id VARCHAR PRIMARY KEY,
    category varchar
);

CREATE TABLE IF NOT EXISTS THE_PRICE_IS_RIGHT(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_user INTEGER,
    id_product INTEGER,
    nb_tries INTEGER,
    FOREIGN KEY (id_product) REFERENCES PRODUCT(id),
    FOREIGN KEY (id_user) REFERENCES USER(id)
);